apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard